//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSDROPLIST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int wID { get; set; }
        public string wName { get; set; }
        public int pID { get; set; }
        public int bID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Province Province { get; set; }
    }
}
